In [28]:
import pandas as pd

In [29]:
coffeeDF=pd.read_csv('coffeeDF.csv')

In [30]:
print(f"\n{coffeeDF.head()}")
print(f"\n{coffeeDF.info()}")
print(f"\n{coffeeDF.describe()}")
print(f"\n{coffeeDF.shape}")

         Day    Coffee  Units Sold
0     Monday  Espresso          23
1     Monday     Latte          34
2    Tuesday  Espresso          34
3    Tuesday     Latte          45
4  Wednesday  Espresso          56
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Day         14 non-null     object
 1   Coffee      14 non-null     object
 2   Units Sold  14 non-null     int64
dtypes: int64(1), object(2)
memory usage: 468.0+ bytes

None

       Units Sold
count   14.000000
mean    53.071429
std     26.042759
min     23.000000
25%     32.500000
50%     45.000000
75%     64.250000
max    100.000000

(14, 3)

In [31]:
# coffeeDF.tail()#deflt. param is 5
coffeeDF.tail(7)

coffeeDF.sample(10)

          Day    Coffee  Units Sold
10   Saturday  Espresso          32
12     Sunday  Espresso         100
11   Saturday     Latte          56
6    Thursday  Espresso          45
4   Wednesday  Espresso          56
7    Thursday     Latte          67
13     Sunday     Latte          98
3     Tuesday     Latte          45
5   Wednesday     Latte          32
0      Monday  Espresso          23

In [32]:
#loc & iloc

#loc: filter by rows & cols of the DF
# coffeeDF.loc[row, col]
# lenDF=len(coffeeDF.loc[0:])
# coffeeDF.loc[lenDF:-1]
coffeeDF.loc[:, "Coffee"]
# print(lenDF)


#iloc
coffeeDF.iloc[0:,0:]
# coffeeDF.iloc[0:,0:1]
# coffeeDF.iloc[0:,0:2]

          Day    Coffee  Units Sold
0      Monday  Espresso          23
1      Monday     Latte          34
2     Tuesday  Espresso          34
3     Tuesday     Latte          45
4   Wednesday  Espresso          56
5   Wednesday     Latte          32
6    Thursday  Espresso          45
7    Thursday     Latte          67
8      Friday  Espresso          89
9      Friday     Latte          32
10   Saturday  Espresso          32
11   Saturday     Latte          56
12     Sunday  Espresso         100
13     Sunday     Latte          98

In [33]:
#at & iat
# coffeeDF.at[1, "Coffee"]
# coffeeDF.iat[1, 1]

In [ ]:
#sorting

# coffeeDF.sort_values("Units Sold", ascending=True)#default
# coffeeDF.sort_values("Units Sold", ascending=False)

coffeeDF.sort_values(["Units Sold", "Coffee"], ascending=False) #will first sort by param. 1, then 2, & bcz "Coffee" vars are alphabetic, it eill sort alphabetically

          Day    Coffee  Units Sold
12     Sunday  Espresso         100
13     Sunday     Latte          98
8      Friday  Espresso          89
7    Thursday     Latte          67
11   Saturday     Latte          56
4   Wednesday  Espresso          56
3     Tuesday     Latte          45
6    Thursday  Espresso          45
1      Monday     Latte          34
2     Tuesday  Espresso          34
5   Wednesday     Latte          32
9      Friday     Latte          32
10   Saturday  Espresso          32
0      Monday  Espresso          23