# Intro to Dataframes

In [100]:
import pandas as pd

df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"], index=["x", "y", "z"]) 
# columns=[] : add column names (default = 0, 1, 2...)
# index=[] : add names to index (default = 0, 1, 2...)

df.head() # show preview of the dataset (default = 5)

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [101]:
df.head(2)

   A  B  C
x  1  2  3
y  4  5  6

In [102]:
df.tail() # show the bottom rows (default = 5)

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [103]:
df.index # .index : access the index , .tolist() : turn it into list

Index(['x', 'y', 'z'], dtype='object')

In [104]:
df.info() # .info() : to see information about the data

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [105]:
df.describe() # for quantitative data, show mean, std, ...

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [106]:
df["A"].unique() # show unique (non-repeacted) values in a column

array([1, 4, 7])

In [107]:
df.nunique() # show how many unique numeric values in all or a column

A    3
B    3
C    3
dtype: int64

In [108]:
df.shape # .shape : tell the shape of the data

(3, 3)

# Loading dataframe

In [109]:
# csv file : .read_csv()
coffee = pd.read_csv("./warmup-data/coffee.csv") # can also paste in website links into the ()

coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [110]:
bios = pd.read_csv("./data/bios.csv")

bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [111]:
# parquet file : .read_parquet()
# excel file : .read_xlsx() - this will take long

# Acessing Data with pandas

In [112]:
coffee.head() # show first 5 rows

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [113]:
coffee.tail(10) # show last 10 rows

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [114]:
coffee.sample(6) # show random rows

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35
10   Saturday    Espresso          45

In [115]:
coffee.sample(7, random_state=1) # random_state=1 : to not change the random sample

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15

In [116]:
coffee.loc[0] # .loc[rows, columns] or [[rows], [columns]] : filter by rows & columns

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [117]:
coffee.loc[[0, 1, 2]] # rows

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [118]:
coffee.loc[4:12, ["Day", "Units Sold"]] # .loc[] : the upper index is inclusive

          Day  Units Sold
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45

In [119]:
coffee.iloc[[1, 2, 3, 4], [0, 2]] # .iloc[] : is same as loc, but it takes index values instead of words

         Day  Units Sold
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

In [120]:
coffee.iloc[3:8] # iloc : the upper index is NOT inclusive

         Day Coffee Type  Units Sold
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30

In [121]:
# change a value in the dataset
coffee.loc[1, "Units Sold"] = 10 # 10 is the index where the value is at

# Ex: [1:3, "Units Sold"] : to change multiple values

coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [122]:
coffee.at[0, "Units Sold"] # .iat[row, column] : get a specific value
# ONLY work on 1 value

np.int64(25)

In [123]:
coffee.iat[0, 2] # .iat[] : same as at[] , but take index values

np.int64(25)

In [124]:
coffee["Units Sold"] # access a column of data

0     25
1     10
2     30
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

In [125]:
coffee.sort_values("Units Sold", ascending=False) # .sort_values() : sort the values in a column
# ascending=True/False : sort in ascending order or not

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [126]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0, 1]) # sort multiple columns at once
# ascending=[0,1] : means "Units Sold" is False, and "Coffee Type" is True
# it's going to sort the "Units Sold" first, then if some values are the same, it is sort the "Coffee Type"

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [127]:
for index, row in coffee.iterrows():
    print(index)
    print(row) # can get a column like row["Units Sold"]
    print()

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

1
Day            Monday
Coffee Type     Latte
Units Sold         10
Name: 1, dtype: object

2
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object

3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object

4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object

5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object

6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object

7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object

8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object

9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object

10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object

11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object

12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object

13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object

# Filtering Data

In [129]:
bios.info()

# we can see that "height_cm" & "weight_kg" are float (quantitative)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [132]:
bios.loc[bios["height_cm"] > 215] # to filter specific values in a column

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5089,5108,Viktor Pankrashkin,1957-06-19,Moskva (Moscow),Moskva,RUS,Soviet Union,220.0,112.0,1993-07-24
5583,5606,Paulinho Villas Boas,1963-01-26,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5716,5739,Uwe Blab,1962-03-26,München (Munich),Bayern,GER,Germany West Germany,218.0,110.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
5796,5819,Andy Campbell,1956-07-21,Melbourne,Victoria,AUS,Australia,218.0,93.0,NaN
6223,6250,Lars Hansen,1954-09-27,København (Copenhagen),Hovedstaden,DEN,Canada,216.0,105.0,NaN
6270,6298,Hu Zhangbao,1963-04-05,NaN,NaN,NaN,People's Republic of China,216.0,135.0,NaN
6409,6440,Sergey Kovalenko,1947-08-11,NaN,NaN,NaN,Soviet Union,216.0,111.0,2004-11-18
6420,6451,Jānis Krūmiņš,1930-01-30,Cēsis,Cēsu novads,LAT,Soviet Union,218.0,141.0,1994-11-20
6504,6537,Luc Longley,1969-01-19,Melbourne,Victoria,AUS,Australia,220.0,135.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN
7074,7111,Paulo da Silva,1963-07-21,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
7188,7226,Vladimir Tkachenko,1957-09-20,Golovinka,Krasnodar Kray,RUS,Soviet Union,220.0,110.0,NaN
7281,7320,Stojko Vranković,1964-01-22,Drniš,Šibensko-kninska županija,CRO,Croatia Yugoslavia,217.0,115.0,NaN
7376,7416,Eurelijus Žukauskas,1973-08-22,Klaipėda,Klaipėda,LTU,Lithuania,218.0,115.0,NaN
52608,52983,Aleksey Kazakov,1976-03-18,Naberezhnye Chelny,Respublika Tatarstan,RUS,Russian Federation,217.0,102.0,NaN
82100,82753,Frédéric Weis,1977-06-22,Thionville,Moselle,FRA,France,218.0,110.0,NaN
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN
107408,108533,Peter John Ramos,1985-05-23,Fajardo,Puerto Rico,PUR,Puerto Rico,219.0,113.0,NaN
112312,113568,Stanko Barać,1986-08-13,Mostar,Hercegovačko-neretvanski kanton,BIH,Croatia,217.0,110.0,NaN
112332,113588,Andreas Glyniadakis,1981-08-26,Chania,Kriti,GRE,Greece,216.0,115.0,NaN
112337,113593,Hamed Haddadi,1985-05-19,Ahvaz,Khuzestan,IRI,Islamic Republic of Iran,218.0,110.0,NaN
118663,120400,Timofey Mozgov,1986-07-16,NaN,NaN,NaN,Russian Federation,216.0,113.0,NaN
118676,120415,Dmitry Musersky,1988-10-29,Makiïvka,Donetsk,UKR,Russian Federation,219.0,104.0,NaN
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN
121694,123709,Salah Mejri,1986-06-15,Jendouba,Jendouba,TUN,Tunisia,216.0,110.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN
130460,133147,Li Muhao,1992-06-02,Guiyang,Guizhou,CHN,People's Republic of China,218.0,115.0,NaN
130461,133148,Zhou Qi,1996-01-16,Xinxiang,Henan,CHN,People's Republic of China,217.0,95.0,NaN
138671,142084,Ondřej Balvín,1992-09-20,Ústí nad Labem,Ústecký kraj,CZE,Czechia,216.0,107.0,NaN
139365,142836,Moustapha Fall,1992-02-23,Paris,Paris,FRA,France,218.0,NaN,NaN

In [135]:
# reduce list
bios.loc[bios["height_cm"] > 215, ["name", "height_cm"]] # show only name, and height > 215cm
# or use : bios[bios["height_cm"] > 215]["name", "height_cm"]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [ ]:
# multiple conditions
bios[(bios["height_cm"] > 215) & (bios["born_country"] == "USA")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [142]:
# example: find name contains "jack", "shaq"
bios[bios["name"].str.contains("jack | shaq", case=False)] # case=False : ignore cases
# | : or,

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1027,1034,Jack Nielsen,1896-08-03,NaN,NaN,NaN,Norway,NaN,NaN,1981-01-09
1141,1148,Jack Butula,1931-01-01,NaN,NaN,NaN,Canada,NaN,NaN,1992-06-26
1182,1189,Jack Keenan,1929-09-14,Montréal,Québec,CAN,Canada,NaN,NaN,2009-06-21
2504,2516,Jack Condon,1903-09-09,Johannesburg,Gauteng,RSA,South Africa,NaN,NaN,1967-01-01
3384,3396,Jack Elliott,1901-10-12,Hoxton,England,GBR,Great Britain,NaN,NaN,1945-07-03
...,...,...,...,...,...,...,...,...,...,...
143657,147311,Jack Williams,2000-04-22,NaN,NaN,NaN,United States,NaN,NaN,NaN
143729,147384,Jack López,1992-12-16,Río Piedras,Puerto Rico,PUR,United States,178.0,73.0,NaN
143795,147451,Jack Leverett,2000-01-18,Bainbridge,Georgia,USA,United States,173.0,NaN,NaN
144292,147980,Jack McBain,2000-01-06,Toronto,Ontario,CAN,Canada,193.0,NaN,NaN
144759,148460,Jack Gower,1994-05-26,NaN,NaN,NaN,Ireland,NaN,NaN,NaN

In [146]:
bios[bios["born_country"].isin(["USA", "FRA"])] # .isin() : check if match a value

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145467,149194,Elisa Nakab,1998-05-08,Briançon,Hautes-Alpes,FRA,Italy,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

In [153]:
# query functions
bios.query('born_country == "USA" or born_country == "FRA"') # .query() : same as the last one, but simpler
# NOTE: use single quotes '' in .query()

# this is the same as : bios[bios["born_country"].isin(["USA", "FRA"])]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145467,149194,Elisa Nakab,1998-05-08,Briançon,Hautes-Alpes,FRA,Italy,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

In [154]:
bios.query('born_country == "USA" and born_city == "Seattle"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN