<a href="https://colab.research.google.com/github/raihansb29/complete-pandas-tutorial/blob/master/Pycaret_main_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Only enable critical logging (Optional)
import os
os.environ["PYCARET_CUSTOM_LOGGING_LEVEL"] = "CRITICAL"

In [1]:
def what_is_installed():
    from pycaret import show_versions
    show_versions()

try:
    what_is_installed()
except ModuleNotFoundError:
    !pip install pycaret
    what_is_installed()

System:
    python: 3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]
executable: /usr/bin/python3
   machine: Linux-6.1.123+-x86_64-with-glibc2.35

PyCaret required dependencies:
                 pip: 24.1.2
          setuptools: 75.2.0
             pycaret: 3.3.2
             IPython: 7.34.0
          ipywidgets: 7.7.1
                tqdm: 4.67.1
               numpy: 1.26.4
              pandas: 2.1.4
              jinja2: 3.1.6
               scipy: 1.11.4
              joblib: 1.3.2
             sklearn: 1.4.2
                pyod: 2.0.5
            imblearn: 0.13.0
   category_encoders: 2.7.0
            lightgbm: 4.6.0
               numba: 0.60.0
            requests: 2.32.3
          matplotlib: 3.7.5
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.24.1
    plotly-resampler: Not installed
             kaleido: 1.0.0
           schemdraw: 0.15
         statsmodels: 0.14.5
              sktime: 0.26.0
               tbats: 1.1.3
            pmdarima: 2.0.4
              psutil: 5.9.5
          markupsafe: 2.0.1
             pickle5: Not installed
         cloudpickle: 3.1.1
         deprecation: 2.1.0
              xxhash: 3.5.0
           wurlitzer: 3.1.1

PyCaret optional dependencies:
                shap: 0.48.0
           interpret: Not installed
                umap: 0.5.9.post2
     ydata_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
          deepchecks: Not installed
             xgboost: 3.0.2
            catboost: Not installed
              kmodes: Not installed
             mlxtend: 0.23.4
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: 0.2.7
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
              gradio: 5.38.2
             fastapi: 0.116.1
             uvicorn: 0.35.0
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: 1.1.7

In [2]:
import time
import numpy as np
import pandas as pd

from pycaret.datasets import get_data
from pycaret.time_series import TSForecastingExperiment

In [3]:
# We want to forecast the next 12 months of data and we will use 3 fold cross-validation to test the models.
fh = 12 # or alternately fh = np.arange(1,13)
fold = 3

In [4]:
# Global Figure Settings for notebook ----
# Depending on whether you are using jupyter notebook, jupyter lab, Google Colab, you may have to set the renderer appropriately
# NOTE: Setting to a static renderer here so that the notebook saved size is reduced.
fig_kwargs = {
    # "renderer": "notebook",
    "renderer": "png",
    "width": 1000,
    "height": 600,
}

In [5]:
# 4. Load your Excel data
file_path = '15skulist.xlsx'  # adjust path as needed
df = pd.read_excel(file_path, engine='openpyxl')
df['Months'] = pd.to_datetime(df['Months'])
df = df.sort_values(['Items', 'Months']).reset_index(drop=True)

In [6]:
# 5. Define global forecasting params
fh = 12      # forecast next 12 months
fold = 3     # 3-fold CV
fig_kwargs = {"renderer": "png", "width": 1000, "height": 600}

In [1]:
import dask
import sktime

print(f"dask version: {dask.__version__}")
print(f"sktime version: {sktime.__version__}")

/usr/lib/python3.11/importlib/__init__.py:126: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  return _bootstrap._gcd_import(name[level:], package, level)

dask version: 2024.12.1
sktime version: 0.26.0

In [9]:
!pip install "dask<2025.0.0"

Collecting dask<2025.0.0
  Downloading dask-2024.12.1-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.11/dist-packages (from dask<2025.0.0) (8.2.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from dask<2025.0.0) (3.1.1)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.11/dist-packages (from dask<2025.0.0) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from dask<2025.0.0) (25.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from dask<2025.0.0) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from dask<2025.0.0) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from dask<2025.0.0) (0.12.1)
Requirement already satisfied: importlib_metadata>=4.13.0 in /usr/local/lib/python3.11/dist-packages (from dask<2025.0.0) (8.7.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib_metadata>=4.13.0->dask<2025.0.0) (3.23.0)
Requirement already satisfied: locket in /usr/local/lib/python3.11/dist-packages (from partd>=1.4.0->dask<2025.0.0) (1.0.0)
Downloading dask-2024.12.1-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 32.4 MB/s eta 0:00:00
Installing collected packages: dask
  Attempting uninstall: dask
    Found existing installation: dask 2025.5.0
    Uninstalling dask-2025.5.0:
      Successfully uninstalled dask-2025.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rapids-dask-dependency 25.6.0 requires dask==2025.5.0, but you have dask 2024.12.1 which is incompatible.
cuml-cu12 25.6.0 requires scikit-learn>=1.5, but you have scikit-learn 1.4.2 which is incompatible.
distributed 2025.5.0 requires dask==2025.5.0, but you have dask 2024.12.1 which is incompatible.
Successfully installed dask-2024.12.1

In [7]:
import matplotlib.pyplot as plt

In [8]:
# 6. Prepare container for all forecasts
all_forecasts = []

# 7. Loop over each SKU
for sku in df['Items'].unique():
    sku_df = df[df['Items'] == sku].copy()
    sku_df = sku_df.set_index('Months').asfreq('MS')  # enforce monthly freq

    # skip if too short for 3 folds + 12-step horizon
    if len(sku_df) < fold + fh:
        print(f"Skipping {sku}: insufficient data ({len(sku_df)} records)")
        continue

    # 8. Initialize PyCaret experiment
    exp = TSForecastingExperiment()
    exp.setup(
        data=sku_df['Sales'],
        fh=fh,
        fold=fold,
        fig_kwargs=fig_kwargs,
        session_id=42,
        verbose=False,
        numeric_imputation_target='mean'
    )

    # 9. Train, tune, finalize
    best = exp.compare_models(sort='MAE')
    tuned = exp.tune_model(best, optimize='MAE')
    final = exp.finalize_model(tuned)

    # 10. Generate forecast DataFrame
    forecast = exp.predict_model(final, fh=fh).reset_index()
    forecast = forecast.rename(columns={'index': 'Months', 'y_pred': 'Sales'})
    forecast['Items'] = sku
    forecast['Type'] = 'Forecast'

    # 11. Append to master list
    all_forecasts.append(forecast[['Months', 'Items', 'Type', 'Sales']])

    # 12. Plot actual + forecast
    plt.figure(figsize=(10, 6))
    # actual historical
    plt.plot(sku_df.index, sku_df['Sales'], label='Actual', color='blue')
    # forecast
    plt.plot(forecast['Months'], forecast['Sales'], label='Forecast', color='red', linestyle='--')
    plt.axvline(sku_df.index[-1], color='gray', linestyle=':', label='Train/Test Split')
    plt.title(f'Forecast for {sku}', fontsize=16)
    plt.xlabel('Months')
    plt.ylabel('Sales')
    plt.legend()
    plt.tight_layout()
    plt.savefig(f'forecast_{sku}.png', dpi=300)
    plt.close()

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 4 candidates, totalling 12 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    0.8s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 4 candidates, totalling 12 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    0.8s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 4 candidates, totalling 12 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    0.8s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 10 candidates, totalling 30 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:    4.9s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 4 candidates, totalling 12 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    0.8s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 4 candidates, totalling 12 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    0.8s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 4 candidates, totalling 12 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    0.8s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 4 candidates, totalling 12 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    0.8s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 10 candidates, totalling 30 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:    2.0s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 10 candidates, totalling 30 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:    4.8s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 10 candidates, totalling 30 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:    2.1s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 10 candidates, totalling 30 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:    2.1s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 10 candidates, totalling 30 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  27 out of  30 | elapsed:    2.0s remaining:    0.2s
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:    2.1s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 10 candidates, totalling 30 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  27 out of  30 | elapsed:    1.9s remaining:    0.2s
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:    1.9s finished

Processing:   0%|          | 0/117 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 3 folds for each of 10 candidates, totalling 30 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  27 out of  30 | elapsed:    1.9s remaining:    0.2s
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:    2.0s finished

In [9]:
# 13. Combine all SKU forecasts and export CSV
if all_forecasts:
    result_df = pd.concat(all_forecasts, ignore_index=True)
    result_df.to_csv('15skulist_all_sku_forecasts.csv', index=False)
    print("✅ All SKU forecasts saved to '15skulist_all_sku_forecasts.csv'")
else:
    print("⚠️ No forecasts generated.")

✅ All SKU forecasts saved to '15skulist_all_sku_forecasts.csv'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [10]:
fc=pd.read_csv('/content/15skulist_all_sku_forecasts.csv')

In [11]:
fc

      Months       Items      Type       Sales
0    2025-06  B10003-2.5  Forecast   3980.0000
1    2025-07  B10003-2.5  Forecast   4710.0000
2    2025-08  B10003-2.5  Forecast   5040.0000
3    2025-09  B10003-2.5  Forecast   5070.0000
4    2025-10  B10003-2.5  Forecast   4300.0000
..       ...         ...       ...         ...
175  2026-01     B8015-5  Forecast  18750.8132
176  2026-02     B8015-5  Forecast  23174.1316
177  2026-03     B8015-5  Forecast  20792.4010
178  2026-04     B8015-5  Forecast  20196.2155
179  2026-05     B8015-5  Forecast  21788.2530

[180 rows x 4 columns]